// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMGNbLrfBWS7DBUmRCyYPPQH65h4OTJ0g',
    appId: '1:265480432953:web:308ec0195a6d8c4ac78ce8',
    messagingSenderId: '265480432953',
    projectId: 'green-plate-b8e68',
    authDomain: 'green-plate-b8e68.firebaseapp.com',
    storageBucket: 'green-plate-b8e68.appspot.com',
    measurementId: 'G-ET5R7MY1D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwSh1Y56RycSbp5UGt7oXVPHhgWT-8F6Q',
    appId: '1:265480432953:android:2e7e2fb58770f9dbc78ce8',
    messagingSenderId: '265480432953',
    projectId: 'green-plate-b8e68',
    storageBucket: 'green-plate-b8e68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQhLvpjg9AHI2R2zxKBjZNDopwaswMxu8',
    appId: '1:265480432953:ios:7a34f2e45a03c432c78ce8',
    messagingSenderId: '265480432953',
    projectId: 'green-plate-b8e68',
    storageBucket: 'green-plate-b8e68.appspot.com',
    iosClientId: '265480432953-59oaq9i8hboqd9gbikdj44hc7t03khlb.apps.googleusercontent.com',
    iosBundleId: 'com.example.freshFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQhLvpjg9AHI2R2zxKBjZNDopwaswMxu8',
    appId: '1:265480432953:ios:d952f9cd40ba0c0ec78ce8',
    messagingSenderId: '265480432953',
    projectId: 'green-plate-b8e68',
    storageBucket: 'green-plate-b8e68.appspot.com',
    iosClientId: '265480432953-gf6t1iakl29rdvr16emuvu4tr3h66sqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.freshFinder.RunnerTests',
  );
}
